# Generated by Django 4.1.4 on 2023-01-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='attachment'),
        ),
    ]
